import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import { ThemeProvider } from '@mui/material/styles';
import CssBaseline from '@mui/material/CssBaseline';

import theme from './muiTheme';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,

}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className={`${inter.className} container mx-auto`}>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <div className="grid grid-cols-1 gap-4">
              <CssBaseline />
              {children}
            </div>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>

    </html >
  );
}
